project_name: ping

before:
  hooks:
  - go mod download

builds:
- binary: ping
  dir: cmd/ping
  goarch:
  - amd64
  - arm
  - arm64
  goarm:
  - 6
  - 7
  goos:
  - darwin
  - freebsd
  - linux
  - windows

archives:
- files:
  - LICENSE
  - README.md
  rlcp: true
  format_overrides:
  - goos: windows
    format: zip
  wrap_in_directory: true

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-{{ .ShortCommit }}"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
