name: CI

on:
  push:
    branches: [ master, release-* ]
    paths-ignore: [ '**.md', '**.png', '**.jpg', '**.svg', '**/docs/**' ]
  pull_request:
    branches: [ master, release-* ]
    paths-ignore: [ '**.md', '**.png', '**.jpg', '**.svg', '**/docs/**' ]
  schedule:
    - cron: '0 4 * * *'

env:
  GO_VERSION: 1.19

jobs:
  test:
    name: Test
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Run Unit tests
        run: make test

  build:
    name: Build
    timeout-minutes: 20
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@v1

      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build
        run: make build
